### ISSUE TITLE
Optimizing Addons and Maps

### ISSUE THREAD

**Issue by SirLich** [SirLich/technical-bedrock#362]
This page would be a top-level explanation of the performance cost associated with various sub-systems. It will be tricky as I would prefer to get tested results, and not just hearsay. 

With that said, I think we could begin with a list of "best practices" as understood by the experienced members of the community.

A few things worth covering:

- What is the performance cost of each subsystem? (entities vs blocks vs items vs particles)
- What is a reasonable cap on texture resolution?
- What is a reasonable cap on bones-per-entity
- How do dummy entities without RP definition compare against proper entities?
- What is the performance of Tags Vs. scoreboards?
- How many commands should you include ontick?
- How to write slow-clocks in tick.json to reduce overhead
- What is the performance costs of using ticking areas? Does total chunks matter more than total ticking areas? 
- Is there any benefit to shortcutting selectors, such as including c=1 first
- Is there any performance benefit to compressing sounds? 
- Are there any particularly heavy entity components, such as AI goals for example?
- What is the performance benifit of using texture_list.json?

Probably way more where that came from ^

**Comment by ghost** [comment]
I can attest only to the efficiency of the biomes and features systems. From my experiences on an iPad Pro (~36 chunk max render distance):

It's challenging to get any biome-specific components to lag generation. Even egregious values for the heightmaps weren't resulting in significant lag. The worse offender was ginormous values for particles storms created by the `"climate"` component.

Features can more obviously cause lag, but radical values have to be used to result in any noticeable effect on chunk load time. Even hundreds of iterations **per chunk** of a multi-block feature seem to come at minimal performance cost. Closer to 1,000 iterations, however, and gameplay will be negatively affected.

**Comment by stirante** [comment]
> What is a reasonable cap on texture resolution?

Absolute maximum is 16k, but reasonable max is 4k, since lower end devices might not support bigger textures.

**Comment by solvedDev** [comment]
> Are there any particularly heavy entity components, such as AI goals for example?

We have noticed pathfinders for flying mobs being really expensive.

Another interesting fact that might be important for people transitioning from Java or Add-On beginners:
For a lot of Java users, extracting commands into individual function files was an important tool to improve performance of command systems. In Bedrock, this is often an anti-pattern or becomes one later in development. That's because you often end up executing a function file on too many entities and therefore too many times. For a lot of cases, this duplicated cost of e.g. executing a scoreboard command outweighs the cost of running an entity selector multiple times.

**Comment by TheRedstoneScientist** [comment]
1. Entities have the biggest performance impact by far. It seems that the complexity of the model surprisingly has little effect on performance except in extreme cases (many thousands of voxels)
2. Our cap internally is no more than 2048 in any dimension and even then you can only have one MAYBE two of those. Remember that all textures are atlased and that can often cause issues on things like mobile and switch.
3. We do not have a cap or guideance on bones per entities. We have not seen any impact on performance.
4. Dummy entities seem to be exactly as heavy as proper entities with the exception of using any navigation/path finding components.
5. No guidance on scoreboards
6. No guidance on command limit
7. Idk
8. Total chunks does matter more than number of tickingareas. Dynamic areas are good to use only when necessary. Good practice is to use a ticking area of ONE chunk for your entire map whenever possible. This will mean doing a lot of vertical redstone.
9. I have not gotten concrete proof but based on what I know about how the game processes selectors, in theory c=1 should optimize things
10. There is ENORMOUS benefit to compressing sound. While you won’t see this effected in things like FPS or tick lag, it has the BIGGEST effect on whether or not your map will perform on older devices or the switch. The number of sounds and the size both matter. You should aim to stream not all of your sounds but any sounds that are over 500kb or over 1 minute in length as general guidance.
11. Flying and pathfinding are the biggest
12. Idk

below are more optimization suggestions from our internal documentation 

When making big chains of commands, always stack them vertically in ONE chunk.
Always try to minimize entities loaded at any given time. Try to keep a MAXIMUM of around 30 (not: we do a bad job of sticking to this number, REALLY bad, but we make up for it in other ways) but it varies depending on entity type. Remember, we want this to work on some old phones.
Use recursion with caution. While it is supported, it can cause performance issues if the recursion is too deep.
Try to minimize the number of commands running per tick.
Do not use a /effect or /gamemode command every tick.
Avoid big clones or fills during runtime. If possible, split this in more than one command that runs on different ticks.
NEVER CROSS CHUNK BOUNDARIES WITH REDSTONE EVER
If possible, unload tickingareas when done with them. You need to use /testforblock to see when the device has finished loading/unloading.
Your “spawnchunks” should be a tickingarea. Try to minimize how many chunks you need for this.
Generally it is better to do things in behaviors and functions than commands.
Flying mobs are a nightmare. Avoid them or try to fake them if you can.
Simulation distance should always be 4 unless you ABSOLUTELY CAN’T
Keep block updates to an absolute minimum
Hollow areas are one of the biggest causes of lag. That’s why builders are required to fill in all unused enclosed spaces. This has something to do with lighting calculations.
Redstone dust causes lag (not as bad as java). Keep dust to a minimum.
It is almost always better to do the alternative that doesn’t use actual redstone
Clean up excess flowing liquids
I can’t think of a good reason to have a sound file longer than 3 minutes
Never rely on bugs. Ever. Future-proof your content to the best of your ability.
Need a randomizer? Use the random argument of scoreboard players or MoLang

**Comment by Sqzrth** [comment]
Maps with a lot of command blocks produces more much lag than using a lot functions.

**Comment by JannisX11** [comment]
Not directly performance related, but the maximum number of textures you should use is around 3000. When you get near 3300, you will start to see purple UI tiles and game crashes on Windows 10. The maximum number of individual textures renderdragon can load is 4096. The vanilla game seems to use around 800 textures as of 1.16, but if course that number will increase in the future with new content.

**Comment by CtrlAltCuteness** [comment]
All redstone components, including Command Blocks, should do their best to stay within single **subchunks**.

Unlike in Java, Redstone won't load neighboring chunks. Also, due to how Bedrock worlds load, the order of loading chunks is also not the same each time (even in a `/tickingarea`), meaning some chunks may load before or even after others when the world loads up / the player enters the area.

Redstone components across **sub**chunk boundaries can get into a frozen state and may need to be replaced (especially true for Command Blocks being powered directly by a repeater / comparator in another chunk).

**Comment by Hatchibombotar** [comment]
If you can use scoreboards rather than tags. At large scales tags cause lag.

**Comment by ToxicMug** [comment]
Is there any performance benefit to compressing sounds?

Yes/No Compressing audio files will reduce your overall rp pack size however all audio is decompressed into wav by the FMod simple API minecraft uses, before being loaded into ram. So no CPU based performance improvements can be gained from compression.

**Comment by StealthyExpertX** [comment]
I'll touch on the subject of lighting in Minecraft.

Lighting is dynamically calculated in Minecraft Bedrock because of this some light-sources have better performance v.s other sources of light.

Light Blocks have the best performance of any light source because they do not render, emit particles, and they have no specific logic tied to them.

All Torches are the least performant sources of light because they emit particles, render and have extra logic connected to check if the block is connected or placed on another block, etc.

Another good alternative to Light Blocks is making a custom block that emits light with no logic added. 

The above method _**^^^**_ isn't as performant but can be far more aesthetically pleasing but still have the benefits of improved performance vs other vanilla light sources.

You can further improve performance by having a map always be set to day or night to prevent the sky-light and block-light having to be recalculated.



Here's a simple lighting performance comparison table that should help with deciding what light sources to use in projects for better performance more points = more of a negative impact on performance. 

The below results are subjective and are based on my experiences while testing light source performance differences.

**Light Blocks: 1 point**
RedstoneUpdates: False
AnimtedTexture: False
LightUpdates: True
TickUpdates: False
Particles: False
Renders: False

**Lanterns: 4 points**
RedstoneUpdates: False
AnimtedTexture: True
LightUpdates: True
TickUpdates: True
Particles: False
Renders: True

**(Basic) Custom Blocks: 2 points**
RedstoneUpdates: False
AnimtedTexture: False
LightUpdates: True
TickUpdates: False
Particles: False
Renders: True

**Red & Brown Mushrooms: 3 points**
RedstoneUpdates: False
AnimtedTexture: False
LightUpdates: True
TickUpdates: True
Particles: False
Renders: True

**Redstone Lamps: 3 points**
RedstoneUpdates: True 
AnimtedTexture: False
LightUpdates: True
TickUpdates: False
Particles: False
Renders: True

**Glowstone:  4 points**
RedstoneUpdates: True
AnimtedTexture: False
LightUpdates: True
TickUpdates: True
Particles: False
Renders: True

**Sea Lanterns:  4 points**
RedstoneUpdates: False
AnimtedTexture: True
LightUpdates: True
TickUpdates: True
Particles: False
Renders: True

**Torches:  4 points**
RedstoneUpdates: False
AnimtedTexture: False
LightUpdates: True
TickUpdates: True
Particles: True
Renders: True

**Redstone Torches:  5 points**
RedstoneUpdates: True
AnimtedTexture: False
LightUpdates: True
TickUpdates: True
Particles: True
Renders: True

**Comment by ghost** [comment]
> I can attest only to the efficiency of the biomes and features systems. From my experiences on an iPad Pro (~36 chunk max render distance):
> 
> It's challenging to get any biome-specific components to lag generation. Even egregious values for the heightmaps weren't resulting in significant lag. The worse offender was ginormous values for particles storms created by the `"climate"` component.
> 
> Features can more obviously cause lag, but radical values have to be used to result in any noticeable effect on chunk load time. Even hundreds of iterations **per chunk** of a multi-block feature seem to come at minimal performance cost. Closer to 1,000 iterations, however, and gameplay will be negatively affected.

Oh. Hmm. The game can apparently run **hundreds of thousands** of iterations of single block features _per chunk_ without inducing a significant performance penalty.

**Comment by DaanV2** [comment]
- **What is the performance cost of each subsystem? (entities vs. blocks vs. items vs. particles)**
Glass blocks are the laggiest block there is.
Surprisingly end rods are about as efficient as sea lanterns.
Anvils are about as efficient as slabs.

- **What is a reasonable cap on texture resolution?**
So I look at this on the scale of objects in the world. And compared it to a block. So a block has 16 pixels on the length/width for a texture. This is noticeable up close, not noticeable from far away.
So for other texture, it doesn't make sense. It goes detailed than 16 pixels per block length.
If you have to, keep it at 128 pixels per block length. any more and a player won't notice any more details on the texture itself.

- **How many commands should you include on tick?**
I try to keep the amount command execute per second as low as possible. to the point of maybe only 20 commands per second to 100 per second.
most command blocks I place execute only on delay or twice per second; very rarely will I use 20-hertz clocks.
Minecraft can quite easily execute hundreds if not thousands of commands in a single go. but make those systems rather only execute when necessary instead of an active system that keeps executing every single tick.
With this, I have had no trouble having huge amounts of command blocks or malfunctions. only resource pack size seemed to influence tier listing badly.

For example:

City maker determines your grid location with hundreds of commands, but that is only done when you place the building.

- **Is there any benefit to shortcutting selectors, such as including c=1 first**
Yes, entity filters especially have to go over the whole list of entities in the world everywhere to filter out on your parameter. Having a count stop enables Minecraft to stop the loop as soon as it found its query.

- **Is there any performance benefit to compressing sounds?**
Only for downloading the RP, the decompressed audio is still loaded into memory unless you are streaming the audio.

- **Are there any particularly heavy entity components, such as AI goals, for example?**
Finding the nearest attackable entity. It has been improved, but in the early days, noticeable lag was found if they had to search huge amounts of huge for entities.
