### ISSUE TITLE
Locators document

### ISSUE THREAD

**Issue by SirLich** [SirLich/technical-bedrock#98]
This is something I'm not very knowledgeable about. I would be interested to get a short doc  explaining them.

**Comment by JannisX11** [comment]
Locators are points on a bone of a geometry that can be used to attach *visual* things like particles and leashes.
Something worth mentioning is that attaching a particle to a locator rotates the particle space by 180° on the X axis. This is because entities are rotated internally by 180° by default and then rotated back to appear correctly in the world.
